apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend_keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend_keycloak
  template:
    metadata:
      labels:
        app: backend_keycloak
    spec:
      containers:
      - name: backend_keycloak
        image: ghcr.io/kyleee0522/springboot_crud_security_keycloak:v1
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: SPRING_DATASOURCE_USERNAME
            value: "edu1"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "New1234!"
          - name: SPRING_DATASOURCE_URL            
            value: "jdbc:mariadb://my-release-mariadb:3306/edu"
          - name: APP_CORS_ALLOWED_ORIGINS            
            value: "frontend_keycloak"          
        ports:
        - containerPort: 8080
