apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-keycloak-ssl
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend-keycloak-ssl
  template:
    metadata:
      labels:
        app: backend-keycloak-ssl
    spec:
      containers:
      - name: backend-keycloak-ssl
        image: ghcr.io/kyleee0522/springboot_crud_security_keycloak:v4
        imagePullPolicy: Always
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "prd"
          - name: SPRING_DATASOURCE_USERNAME
            value: "edu1"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "New1234!"
          - name: SPRING_DATASOURCE_URL            
            value: "jdbc:mariadb://211.43.12.162:31381/edu"
          - name: APP_CORS_ALLOWED_ORIGINS            
            value: "frontend-keycloak-ssl"
          - name: SERVER_PORT            
            value: "8080" 
        ports:
        - containerPort: 8080
