apiVersion: v1	
kind: Service	
metadata:	
  name: backend_keycloak
  labels:
    app: backend_keycloak
spec:	
  ports:	
  - port: 9080	
    targetPort: 8080
    name: http
  selector:	
    app: backend_keycloak
  type: ClusterIP
